# Generated by Django 4.2.1 on 2023-06-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_utente', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('commento', models.TextField()),
            ],
        ),
    ]
