# Generated by Django 4.2.1 on 2023-06-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_commentsectionmodel_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsectionmodel',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
