# Generated by Django 4.2.1 on 2023-06-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_post_author_remove_post_tags_post_caption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_name',
            new_name='image',
        ),
    ]
