# Generated by Django 4.2.1 on 2023-09-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_rename_image_name_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(null=True),
        ),
    ]
